# /mission/add endpoint tests

@baseUrl = http://localhost:3000
@endPoint = /api/mission/check
@files = ./files

###
# normal case
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo"
Content-Type: application/octet-stream

< ./{{files}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo

------WebKitFormBoundaryWmunjnPoLceaU7KM--

###
# forces check to return non-conformity (pbo file name not respecting convention)
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="test_1.pbo"
Content-Type: application/octet-stream

< ./{{files}}/test_1.pbo

------WebKitFormBoundaryWmunjnPoLceaU7KM--

###
# not a pbo file or corrupted pbo
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="easy.jpg"
Content-Type: application/octet-stream

< ./{{files}}/easy.jpg

------WebKitFormBoundaryWmunjnPoLceaU7KM--

###
# maxFileSize exceeded
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="maxFileSize.pdf"
Content-Type: application/octet-stream

< ./{{files}}/maxFileSize.pdf

------WebKitFormBoundaryWmunjnPoLceaU7KM--

###
# bad request : incomplete form
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="test.pbo"
Content-Type: application/octet-stream

------WebKitFormBoundaryWmunjnPoLceaU7KM--
