# /mission/add endpoint tests
###
# API documentation generation :
# jsdoc -t ./node_modules/ink-docstrap/template/ -d ./doc -R ../README.md -c ./jsdoc.conf
###
@baseUrl = http://localhost:3000
@endPoint = /api/mission/add
@files = ./files

###
# Login
# After authentification, return an access_token in the url
#
GET https://gdc-toolbox-api.eu.auth0.com/authorize
    ?response_type=token
    &client_id=4PQWGF6GSh99iHnZxjmLIxUhldBqnuFm
    &redirect_uri=http://localhost:3000/api/mission/list
    &scope=openid%20profile%20email
    &audience=https://grecedecanards.fr/api-dev
    &state=xyzABC123
    &connection=google-oauth2

###
# Requests token
# unusefuul if response-type=token, as above
#
POST https://gdc-toolbox-api.eu.auth0.com/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=authorization_code
&client_id=4PQWGF6GSh99iHnZxjmLIxUhldBqnuFm
&client_secret=dBcvFNJuylPj7QsPiA30V8fzUaHfnYToODbHaaen7OJ68e1t-LMzhYXhdcfvxR8Z
&code=-YxaOCbO7fI8V4dvP
&state=xyzABC123
&redirect_uri=http://localhost:3000/api/mission/add

###
# Gets user info
GET https://gdc-toolbox-api.eu.auth0.com/userinfo
Authorization: Bearer ""


###
# normal case
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
authorization: Bearer ACCESS_TOKEN
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo"
Content-Type: application/octet-stream

< ./{{files}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo

------WebKitFormBoundaryWmunjnPoLceaU7KM--

###
# forces check to return non-conformity (pbo file name not respecting convention)
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="test_1.pbo"
Content-Type: application/octet-stream

< ./{{files}}/test_1.pbo

------WebKitFormBoundaryWmunjnPoLceaU7KM--

###
# not a pbo file or corrupted pbo
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="easy.jpg"
Content-Type: application/octet-stream

< ./{{files}}/easy.jpg

------WebKitFormBoundaryWmunjnPoLceaU7KM--

###
# maxFileSize exceeded
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="maxFileSize.pdf"
Content-Type: application/octet-stream

< ./{{files}}/maxFileSize.pdf

------WebKitFormBoundaryWmunjnPoLceaU7KM--

###
# bad request : incomplete form
POST {{baseUrl}}{{endPoint}} HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWmunjnPoLceaU7KM

------WebKitFormBoundaryWmunjnPoLceaU7KM
Content-Disposition: form-data; name="file"; filename="test.pbo"
Content-Type: application/octet-stream

------WebKitFormBoundaryWmunjnPoLceaU7KM--
