@baseUrl = http://localhost:3000
@endPoint = /api/mission/update

###
# normal case for missionIsPlayable
PUT {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo/?missionIsPlayable=true HTTP/1.1
content-type: text/html

###
# normal case for isMissionArchived
PUT {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo/?isMissionArchived=true HTTP/1.1
content-type: text/html

###
# non-existent pbo in database of published missions
PUT {{baseUrl}}{{endPoint}}/non-existent.pbo/?missionIsPlayable=true HTTP/1.1
content-type: text/html

###
# no parameter in query
PUT {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo/ HTTP/1.1
content-type: text/html

###
# wrong number of parameters in query
PUT {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo/?isMissionArchived=true&missionIsPlayable=true HTTP/1.1
content-type: text/html

###
# missing parameter in query
PUT {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo/?isMissionArchived HTTP/1.1
content-type: text/html

###
# illegal value for update
PUT {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo/?isMissionArchived="toto" HTTP/1.1
content-type: text/html

###
# key not allowed for update
PUT {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo/?isMissionValid="true" HTTP/1.1
content-type: text/html

###
# Bad-request
PUTS {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo HTTP/1.1
content-type: text/html
