@baseUrl = http://localhost:3000/api

###
# normal case
GET {{baseUrl}}/mission/list HTTP/1.1
content-type: text/html

###
# Bad-request
GETs {{baseUrl}}/mission/list HTTP/1.1
content-type: text/html
