@baseUrl = http://localhost:3000
@endPoint = /api/mission/show

###
# normal case
GET {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo HTTP/1.1
content-type: text/html

###
# non-existent pbo in database of published missions
GET {{baseUrl}}{{endPoint}}/non-existent.pbo HTTP/1.1
content-type: text/html

###
# Bad-request
GETS {{baseUrl}}{{endPoint}}/CPC-CO[25]-WelcomeToTheJungle-V2.pja305.pbo HTTP/1.1
content-type: text/html
